networks:

  stremionetwork:
    name: stremionetwork
    ipam:
      config:
        - subnet: 172.40.0.0/24

services:

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    ports:
      - 9117:9117
    volumes:
      - ./jackett/config:/config
      - ./jackett/downloads:/downloads
    env_file:
      - ./jackett/.env
    restart: unless-stopped
    networks:
      stremionetwork:
        ipv4_address: 172.40.0.2

  jackett-plugin:
    image: ghcr.io/asirkov/jackett-plugin:latest
    platform: linux/arm64/v8
    container_name: jackett-plugin
    ports:
      - 7000:7000
    env_file:
      - ./jackett-plugin/.env
    restart: unless-stopped
    networks:
      stremionetwork:
        ipv4_address: 172.40.0.3

  stremio-web:
    build: ./stremio-web
    container_name: stremio-web
    ports:
      - 8888:80
    restart: unless-stopped
    networks:
      stremionetwork:
        ipv4_address: 172.40.0.4
  
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      --interval 300
      --cleanup
      jackett-plugin
    restart: always
    networks:
      stremionetwork:
        ipv4_address: 172.40.0.5
